### ISSUE TITLE
fuzzy partition coefficient (FPC)? missing

### ISSUE THREAD

**Issue by Nandreasyan** [omadson/fuzzy-c-means#14] opened 2020-12-06 17:55 UTC
The fuzzy partition coefficient (FPC) is missing? To be able to find best number of clusters.

**Comment by omadson** [comment] 2020-12-07 12:11
Hi, @Nandreasyan, I didn't implement the fuzzy partition coefficient, but I read section 4.3.3.2. of the paper [On clustering validation techniques](https://link.springer.com/article/10.1023%2FA%3A1012801612483) and verified that there are some legal metrics to be implemented. I will list below the metrics that I will implement in the next few days

 - [ ] Partition coefficient
 - [ ] Partition entropy
 - [ ] Purity

**Comment by Nandreasyan** [comment] 2020-12-07 13:11
I took the  function _fp_coeff(u) from scikit-fuzzy (skfuzzy)  and put it tehre as you provided in your librery

**Comment by omadson** [comment] 2020-12-07 17:51
@Nandreasyan, I created a release to add what you had requested. To install just use:

```
pip install fuzzy-c-means==1.2.2
```

**Comment by Nandreasyan** [comment] 2020-12-07 17:55
Thank you, but unfortunately I get an error

pip install fuzzy-c-means==1.2.2
ERROR: Could not find a version that satisfies the requirement fuzzy-c-means==1.2.2
ERROR: No matching distribution found for fuzzy-c-means==1.2.2

(virtenv) XXXXXX\fuzzyclustering>pip install fuzzy-c-means
Requirement already satisfied: fuzzy-c-means in XXXXXX\fuzzyclustering\virtenv\lib\site-packages (0.0.6)
Requirement already satisfied: scipy>=1.1.0 in XXXXXX\fuzzyclustering\virtenv\lib\site-packages (from fuzzy-c-means) (1.5.4)
Requirement already satisfied: numpy>=1.15.4 in XXXXXX\fuzzyclustering\virtenv\lib\site-packages (from fuzzy-c-means) (1.19.4)
Requirement already satisfied: numpy>=1.15.4 in XXXXXX\fuzzyclustering\virtenv\lib\site-packages (from fuzzy-c-means) (1.19.4)

**Comment by omadson** [comment] 2020-12-07 17:59
This is weird. Try this:
```
pip install fuzzy-c-means -U
```
Note: If you are using google collab, it may be that it has not updated the pypi database.

**Comment by Nandreasyan** [comment] 2020-12-07 18:04
Actually I am not using google collab,  for pip install fuzzy-c-means -U is the same as without -U
Python 3.7.9
pip 20.3.1

**Comment by omadson** [comment] 2020-12-07 18:14
I don't understand, it seems to me that it is because it has a version of fuzzy-c-means in the cache... So.. try to use:

```
pip install --upgrade --force-reinstall fuzzy-c-means
```

**Comment by Nandreasyan** [comment] 2020-12-07 18:16
pip install --upgrade --force-reinstall fuzzy-c-means

......
Attempting uninstall: fuzzy-c-means
    Found existing installation: fuzzy-c-means 0.0.6
    Uninstalling fuzzy-c-means-0.0.6:
      Successfully uninstalled fuzzy-c-means-0.0.6
Successfully installed fuzzy-c-means-0.0.6 numpy-1.19.4 scipy-1.5.4

**Comment by Nandreasyan** [comment] 2020-12-07 18:17
in your __init__.py 
"""fuzzy-c-means - A simple implementation of Fuzzy C-means algorithm."""
from .fcm import FCM

__version__ = '0.0.6'
__author__ = 'Madson Dias <madsonddias@gmail.com>'
__all__ = ['FCM']

This is the problem perhaps?

**Comment by omadson** [comment] 2020-12-07 18:19
Yeah, guy.. can be this. I will change these lines.

**Comment by omadson** [comment] 2020-12-07 18:22
I modified this and created a new release. I had already tested it on my computer and it worked, I don't understand why it didn't work on yours. Please try and tell me what happened.

**Comment by Nandreasyan** [comment] 2020-12-07 18:24
The same, it takes again 0.06 version

**Comment by omadson** [comment] 2020-12-07 18:34
Can you create a new virtual environment and try to install everything again? It's working perfectly for me.

**Comment by Nandreasyan** [comment] 2020-12-07 18:56
I have just done the following.

python -m pip cache purge
I have created new environment, updated the pip and installed your library again the same.
(envtesst) λ pip install fuzzy-c-means
Collecting fuzzy-c-means
  Downloading fuzzy_c_means-0.0.6-py3-none-any.whl (3.5 kB)
Collecting numpy>=1.15.4
  Downloading numpy-1.19.4-cp37-cp37m-win_amd64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 3.3 MB/s
Collecting scipy>=1.1.0
  Downloading scipy-1.5.4-cp37-cp37m-win_amd64.whl (31.2 MB)
     |████████████████████████████████| 31.2 MB 3.3 MB/s
Installing collected packages: numpy, scipy, fuzzy-c-means
Successfully installed fuzzy-c-means-0.0.6 numpy-1.19.4 scipy-1.5.4

(envtesst) λ pip install fuzzy-c-means==1.2.3
ERROR: Could not find a version that satisfies the requirement fuzzy-c-means==1.2.3
ERROR: No matching distribution found for fuzzy-c-means==1.2.3

**Comment by Nandreasyan** [comment] 2020-12-07 19:10
In PyCharm can see that the latest version is 1.2.3, but can not update it. I do not know what else I can do to install the new version.

**Comment by omadson** [comment] 2020-12-07 19:14
Now I know where the problem is. Your version of python is not allowed by the package requirements. Would I have to change the python version to >=3.8? You can use [pyenv](https://github.com/pyenv/pyenv) to do this.

**Comment by Nandreasyan** [comment] 2020-12-07 19:29
Python 3.8.6

pip install fuzzy-c-means
Collecting fuzzy-c-means
  Downloading fuzzy_c_means-1.2.3-py3-none-any.whl (6.2 kB)
  Downloading fuzzy_c_means-1.2.2-py3-none-any.whl (6.2 kB)
  Downloading fuzzy_c_means-1.2.1-py3-none-any.whl (6.1 kB)
  Downloading fuzzy_c_means-1.0.0-py3-none-any.whl (6.0 kB)
Collecting numpy<2.0.0,>=1.19.2
  Downloading numpy-1.19.4-cp38-cp38-win_amd64.whl (13.0 MB)
     |████████████████████████████████| 13.0 MB 3.3 MB/s
Installing collected packages: numpy, fuzzy-c-means
Successfully installed fuzzy-c-means-1.0.0 numpy-1.19.4

pip install fuzzy-c-means==1.2.3
Collecting fuzzy-c-means==1.2.3
  Using cached fuzzy_c_means-1.2.3-py3-none-any.whl (6.2 kB)
ERROR: Could not find a version that satisfies the requirement jaxlib<0.2.0,>=0.1.57 (from fuzzy-c-means)
ERROR: No matching distribution found for jaxlib<0.2.0,>=0.1.57

pip install jaxlib
ERROR: Could not find a version that satisfies the requirement jaxlib
ERROR: No matching distribution found for jaxlib

**Comment by Nandreasyan** [comment] 2020-12-07 19:43
jaxlib even I can not install with python 3.9.
It seems jaxlib have  problems with windows, or I need to manually install without pip

**Comment by Nandreasyan** [comment] 2020-12-07 19:45
Perhaps it make sense to have 2 versions of the library one with jaxlib one without jaxlib

**Comment by omadson** [comment] 2020-12-07 20:48
Yeah, it's a problem. A solution is to copy my old code and use it in your own repository. Look at this [gist](https://gist.github.com/omadson/1aefe4f69c25ec79487fdedde58c9c6d). I modified to compute the partition coefficient. You can add this file on your repository and call using:

```Python
from .fcm import FCM
```
I think this will solve your problem.

**Comment by omadson** [comment] 2020-12-07 20:51
in the next few days I will return the previous dependencies and create a different package that uses JAX as a dependency.

**Comment by Nandreasyan** [comment] 2020-12-07 21:41
> Yeah, it's a problem. A solution is to copy my old code and use it in your own repository. Look at this [gist](https://gist.github.com/omadson/1aefe4f69c25ec79487fdedde58c9c6d). I modified to compute the partition coefficient. You can add this file on your repository and call using:
> 
> ```python
> from .fcm import FCM
> ```
> 
> I think this will solve your problem.

Thank you

**Comment by omadson** [comment] 2020-12-07 22:06
Your welcome.

I'm closing the issue.

**Closed by omadson** 2020-12-07 22:06 UTC
Labels: good first issue
